-- ============================================================================
--  WORK TRACKER — IT SUPPORT TICKETS
--
--  Run this once in:  Supabase → SQL Editor → New query → Run
--  Safe to re-run: every statement is idempotent (create … if not exists /
--  drop-then-create / create or replace), so a second run changes nothing.
--  A brand-new database built from supabase/schema.sql already has all of it.
--
--  What it adds
--    1. the `it_support.manage` capability key on workers.permissions
--    2. public.is_it_support() — true only for a WORKER whose row carries the
--       key. The admin is false here on purpose, exactly like the client-side
--       `isItSupport()` in src/lib/tickets.ts: running support is a worker's
--       job, and the ticket queue is not part of the owner's capability set.
--    3. tickets + ticket_replies, with RLS:
--         · anyone signed in may submit (and read) their own ticket
--         · only IT Support may read the whole queue, triage or assign
--    4. public.it_support_holders() — the people a ticket can be assigned to
--    5. 'ticket' as a valid notifications.type + notifications.ticket_id
--    6. the notification fan-out, as SECURITY DEFINER triggers. It cannot be
--       done from the app: `notifications_insert` RLS lets a worker insert only
--       their own notifications (plus the admin's), and who runs IT Support is
--       not the submitter's business. The database tells the desk instead:
--         · a submitted ticket notifies every grant holder
--         · a reply notifies the other side of the conversation
--         · a status change notifies the requester
-- ============================================================================

-- ---------- 1. the capability key ----------
-- Same list as before, plus the new key. Without this, saving a worker with IT
-- Support ticked would be rejected by the constraint.
alter table public.workers drop constraint if exists workers_permissions_valid;
alter table public.workers add constraint workers_permissions_valid check (
  permissions <@ array[
    'dashboard.view',
    'workers.view',
    'workers.manage',
    'entries.view_all',
    'entries.manage',
    'tasks.view_all',
    'tasks.manage_all',
    'priority_board.view',
    'meetings.view',
    'invoices.view',
    'payments.view_all',
    'payments.manage',
    'finance.view',
    'finance.manage',
    'finance.subscription',
    'finance.payroll',
    'reports.view',
    'clients.manage',
    'settings.manage',
    -- The support desk. Note what it is NOT: a capability the admin holds.
    'it_support.manage'
  ]::text[]
);

-- ---------- 2. is_it_support() ----------
-- Deliberately NOT has_permission('it_support.manage'): that helper answers
-- true for the admin for every key. This one reads the caller's own worker row
-- and nothing else, so the admin — who has no worker row — is always false.
create or replace function public.is_it_support()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select coalesce(
    (select 'it_support.manage' = any(w.permissions)
       from public.profiles p
       join public.workers w on w.id = p.worker_id
      where p.user_id = auth.uid() and p.role = 'worker'),
    false
  );
$$;

revoke all on function public.is_it_support() from public, anon;
grant execute on function public.is_it_support() to authenticated;

-- ---------- 3. the tables ----------
-- `number` is the short handle people quote ("ticket #12"). It is an identity
-- column so two people submitting at the same moment cannot collide on it.
create table if not exists public.tickets (
  id                uuid primary key default gen_random_uuid(),
  number            bigint generated by default as identity,
  subject           text not null,
  description       text not null,
  category          text not null default 'other' check (category in ('hardware','software','account','other')),
  priority          text not null default 'medium' check (priority in ('low','medium','high')),
  status            text not null default 'open' check (status in ('open','in_progress','resolved')),
  -- Who reported it. Snapshotted as a name as well: the desk reads the queue
  -- without needing to open the workers list.
  requester_user_id uuid not null references auth.users (id) on delete cascade,
  requester_name    text not null default 'A teammate',
  -- Who is handling it — always someone with the IT Support grant.
  assignee_user_id  uuid references auth.users (id) on delete set null,
  assignee_name     text,
  -- Downscaled screenshots as data URLs (see src/lib/image.ts). Capped at 3 by
  -- the app; the check here is the backstop for anything writing directly.
  attachments       text[] not null default '{}'::text[] check (array_length(attachments, 1) is null or array_length(attachments, 1) <= 3),
  reply_count       integer not null default 0,
  created_at        timestamptz not null default now(),
  updated_at        timestamptz not null default now(),
  resolved_at       timestamptz
);

create index if not exists tickets_created_idx on public.tickets (created_at desc);
create index if not exists tickets_requester_idx on public.tickets (requester_user_id, created_at desc);
create index if not exists tickets_status_idx on public.tickets (status, priority);

create table if not exists public.ticket_replies (
  id             uuid primary key default gen_random_uuid(),
  ticket_id      uuid not null references public.tickets (id) on delete cascade,
  author_user_id uuid not null references auth.users (id) on delete cascade,
  author_name    text not null default 'A teammate',
  -- true when the author holds the IT Support grant. Enforced by the insert
  -- policy below, so a requester cannot fake a message from the desk.
  from_support   boolean not null default false,
  body           text not null,
  created_at     timestamptz not null default now()
);

create index if not exists ticket_replies_ticket_idx on public.ticket_replies (ticket_id, created_at);

-- ---------- 4. RLS ----------
alter table public.tickets enable row level security;
alter table public.ticket_replies enable row level security;

-- The queue belongs to IT Support; everyone else sees exactly the tickets they
-- submitted. That second clause is what lets a requester open their own ticket
-- from a bell notification without ever seeing anyone else's.
drop policy if exists "tickets_select" on public.tickets;
create policy "tickets_select" on public.tickets
  for select using (
    (select public.is_it_support())
    or requester_user_id = (select auth.uid())
  );

-- Submitting is open to everyone who is signed in — workers, IT Support and
-- the admin included. The row must be their own; they cannot file as someone
-- else ("on behalf of" is a conversation, not a data path).
drop policy if exists "tickets_insert" on public.tickets;
create policy "tickets_insert" on public.tickets
  for insert with check (requester_user_id = (select auth.uid()));

-- Triage — status, assignee — is IT Support's alone. The after-trigger below
-- moves reply_count / updated_at / resolved_at.
drop policy if exists "tickets_update" on public.tickets;
create policy "tickets_update" on public.tickets
  for update using ((select public.is_it_support())) with check ((select public.is_it_support()));

drop policy if exists "tickets_delete" on public.tickets;
create policy "tickets_delete" on public.tickets
  for delete using ((select public.is_it_support()));

-- Replies are readable by the desk and by the ticket's own requester.
drop policy if exists "ticket_replies_select" on public.ticket_replies;
create policy "ticket_replies_select" on public.ticket_replies
  for select using (
    (select public.is_it_support())
    or exists (
      select 1 from public.tickets t
       where t.id = ticket_id and t.requester_user_id = (select auth.uid())
    )
  );

-- …and writable by the same two parties. `from_support` must agree with the
-- caller's actual standing, so the badge in the thread cannot be spoofed.
drop policy if exists "ticket_replies_insert" on public.ticket_replies;
create policy "ticket_replies_insert" on public.ticket_replies
  for insert with check (
    author_user_id = (select auth.uid())
    and from_support = (select public.is_it_support())
    and (
      (select public.is_it_support())
      or exists (
        select 1 from public.tickets t
         where t.id = ticket_id and t.requester_user_id = (select auth.uid())
      )
    )
  );

-- ---------- 5. who can be assigned ----------
-- SECURITY DEFINER: the desk may not be able to select other profiles directly,
-- and this is a deliberately small, non-sensitive answer — the names of the
-- people already running support. Non-support callers get no rows.
create or replace function public.it_support_holders()
returns table (user_id uuid, name text)
language sql
stable
security definer
set search_path = public
as $$
  select p.user_id, w.name
    from public.workers w
    join public.profiles p on p.worker_id = w.id
   where p.role = 'worker'
     and w.permissions @> array['it_support.manage']::text[]
     and public.is_it_support()
   order by w.name;
$$;

revoke all on function public.it_support_holders() from public, anon;
grant execute on function public.it_support_holders() to authenticated;

-- ---------- 6. notifications: the new type + the ticket link ----------
alter table public.notifications add column if not exists ticket_id uuid
  references public.tickets (id) on delete cascade;

alter table public.notifications drop constraint if exists notifications_type_check;
alter table public.notifications
  add constraint notifications_type_check
  check (type in ('note','time_in','time_out','time_added','payment','break_start','break_end','chat','ticket'));

-- ---------- 7. the fan-out ----------
-- One trigger function for all three moments, because they all need the same
-- two things: the ticket row, and the list of people running support.
create or replace function public.notify_ticket_event()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  t            public.tickets;
  ref          text;
  v_recipient  uuid;
  v_status     text;
begin
  if tg_table_name = 'ticket_replies' then
    select * into t from public.tickets where id = new.ticket_id;
    if not found then
      return new;
    end if;
    -- Keep the queue row honest: the newest activity floats up and the reply
    -- count is right even when the requester (who cannot update tickets under
    -- RLS) is the one writing.
    update public.tickets
       set reply_count = reply_count + 1,
           updated_at  = now()
     where id = new.ticket_id;
    ref := '#' || t.number;

    if new.from_support then
      -- The desk answered: the requester hears about it, unless they are the
      -- one typing (which the RLS insert policy already disallows).
      if t.requester_user_id <> new.author_user_id then
        insert into public.notifications (user_id, entry_id, ticket_id, type, message)
        values (t.requester_user_id, null, t.id, 'ticket',
                'IT Support replied on ' || ref || ' — ' || t.subject);
      end if;
    else
      -- The requester wrote back: the assignee if the ticket is claimed,
      -- otherwise everyone on the desk.
      if t.assignee_user_id is not null and t.assignee_user_id <> new.author_user_id then
        insert into public.notifications (user_id, entry_id, ticket_id, type, message)
        values (t.assignee_user_id, null, t.id, 'ticket',
                t.requester_name || ' replied on ' || ref || ' — ' || t.subject);
      else
        for v_recipient in
          select p.user_id
            from public.workers w
            join public.profiles p on p.worker_id = w.id
           where p.role = 'worker'
             and w.permissions @> array['it_support.manage']::text[]
             and p.user_id <> new.author_user_id
             and p.user_id <> t.requester_user_id
        loop
          insert into public.notifications (user_id, entry_id, ticket_id, type, message)
          values (v_recipient, null, t.id, 'ticket',
                  t.requester_name || ' replied on ' || ref || ' — ' || t.subject);
        end loop;
      end if;
    end if;

    return new;
  end if;

  -- tickets: an insert (a new ticket) or a status change.
  if tg_op = 'INSERT' then
    ref := '#' || new.number;
    -- Every grant holder except the submitter — which for a ticket raised by
    -- the desk itself means the rest of the desk, and for the admin's own
    -- ticket means everyone running support.
    for v_recipient in
      select p.user_id
        from public.workers w
        join public.profiles p on p.worker_id = w.id
       where p.role = 'worker'
         and w.permissions @> array['it_support.manage']::text[]
         and p.user_id <> new.requester_user_id
    loop
      insert into public.notifications (user_id, entry_id, ticket_id, type, message)
      values (v_recipient, null, new.id, 'ticket',
              new.requester_name || ' submitted ticket ' || ref || ' — ' || new.subject);
    end loop;
    return new;
  end if;

  if tg_op = 'UPDATE' then
    -- Moving a ticket along is how the requester learns it is being handled.
    update public.tickets
       set resolved_at = case when new.status = 'resolved' then coalesce(old.resolved_at, now()) else null end,
           updated_at  = now()
     where id = new.id;

    if new.requester_user_id <> coalesce(auth.uid(), new.requester_user_id)
       and new.status is distinct from old.status then
      v_status := case new.status
                    when 'open' then 'Open'
                    when 'in_progress' then 'In progress'
                    else 'Resolved'
                  end;
      insert into public.notifications (user_id, entry_id, ticket_id, type, message)
      values (new.requester_user_id, null, new.id, 'ticket',
              '#' || new.number || ' is now ' || v_status || ' — ' || new.subject);
    end if;
    return new;
  end if;

  return new;
end;
$$;

revoke all on function public.notify_ticket_event() from public, anon;

drop trigger if exists tickets_notify_created on public.tickets;
create trigger tickets_notify_created
  after insert on public.tickets
  for each row execute function public.notify_ticket_event();

drop trigger if exists tickets_notify_status on public.tickets;
create trigger tickets_notify_status
  after update of status on public.tickets
  for each row
  when (old.status is distinct from new.status)
  execute function public.notify_ticket_event();

drop trigger if exists ticket_replies_notify on public.ticket_replies;
create trigger ticket_replies_notify
  after insert on public.ticket_replies
  for each row execute function public.notify_ticket_event();

-- ---------- 8. table privileges (RLS narrows them per row) ----------
grant select, insert, update, delete on public.tickets to authenticated;
grant select, insert on public.ticket_replies to authenticated;
